In [1]:
# Importing all Libraries
import pandas as pd
import numpy as np

In [19]:
# read the datafile
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [21]:
#Convert categorical data to numerical data
dataset=pd.get_dummies(dataset, drop_first = True,dtype = int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [23]:
#Remove the unwanted data
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [25]:
#calculate the no of parameters to be classified in the output
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [29]:
#Define the inputs and output from the given dataset
independent = dataset[["Age","EstimatedSalary","Gender_Male"]]
dependent = dataset["Purchased"]

In [31]:
independent.shape

(400, 3)

In [33]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [35]:
#Split the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [37]:
#Model generation
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion ="entropy", random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [39]:
y_pred = classifier.predict(x_test)

In [41]:
#Evaluation Metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[71  8]
 [ 3 38]]


In [47]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        79
           1       0.83      0.93      0.87        41

    accuracy                           0.91       120
   macro avg       0.89      0.91      0.90       120
weighted avg       0.91      0.91      0.91       120



In [53]:
classifier.predict([[400,30,1]])


C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [61]:
#SAve file - best model
import pickle
filename = "final_model.sav"
pickle.dump(classifier,open(filename,'wb'))

In [63]:
#Deployment of model
loaded_model=pickle.load(open("final_model.sav",'rb'))
result = loaded_model.predict([[400,30,1]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)